### ISSUE TITLE
Is Step 2 "generate_images.py" supposed to be using GPU?

### ISSUE THREAD

**Issue by XcloudFance** [Picsart-AI-Research/OpenBias#3]
Hi, I truly appreciate for the release of the work. When I was trying to run the whole pipeline, is it still required to do the first step if already downloading the json file from here?

And also, when I was running Step2, it seems to me that somehow the code runs very slow. Therefore I checked Nvidia-smi and turned out it was not using GPUs at all. I think it is supposed to use GPU to generate biased images, right?

**Comment by XcloudFance** [comment]
Alright turned it out the trouble should be attributed to TMUX issues. If anyone using TMUX on this project, it wont even run seriously.

But before I also run it somewhere, it is not taking GPU and run slowly. I couldnt even tell if they are using CPU. How come this code is so absurd in this way..

**Comment by XcloudFance** [comment]
Ok since the team is not replying, I solved it individually.

Just go to the generate_images.py and prompt Claude to change it to Accelerate library.

Then in the sh script, change it to below:
CUDA_VISIBLE_DEVICES=0 accelerate launch acce.py --dataset coco --generator sd-2


which means you are going to use accelerate to run the program.

**Comment by Moreno98** [comment]
Hi, thank you for your interest in our work.

1) You don't need to run step 1 if you already downloaded the proposed biases.

2) All the code steps are optimized to run on multiple GPUs. Tmux should not interfere with this. 
The `generate_images.py` script uses DDP to distribute on multi-GPU, thus you could have an issue with DDP (e.g., the `MASTER_PORT` under `utils/DDP_manager`).
If you fixed it with accelerate, make sure DDP is working if you are using multiple GPUs. You could also try torchrun. 

If you provide more details about the GPU issue (e.g., errors) I will be happy to help you more.

**Comment by XcloudFance** [comment]
> Hi, thank you for your interest in our work.
> 
> 1. You don't need to run step 1 if you already downloaded the proposed biases.
> 2. All the code steps are optimized to run on multiple GPUs. Tmux should not interfere with this.
>    The `generate_images.py` script uses DDP to distribute on multi-GPU, thus you could have an issue with DDP (e.g., the `MASTER_PORT` under `utils/DDP_manager`).
>    If you fixed it with accelerate, make sure DDP is working if you are using multiple GPUs. You could also try torchrun.
> 
> If you provide more details about the GPU issue (e.g., errors) I will be happy to help you more.


Hi, Thanks for the response. In fact you are right about the NCCL configuration. I should be checking it back if anything wrong with it.
